### ISSUE TITLE
Chapter 19: andWhere on a manually-defined Many-To-Many relation

### ISSUE THREAD

**Issue by ZaneCEO** [knpuniversity/doctrine-queries#5]
The last few cautioning words on https://symfonycasts.com/screencast/doctrine-relations/many-to-many-joins are about the limit of Many-To-Many: you can't add extra data.

So I build a `TagArticle` entity, as suggested in the chapter. It has:

- article field: a Many-To-One relationship to the Article entity
- tag field: a Many-To-One relationship to the Tag entity
- additional metadata fields

````
/**
 * @ORM\Entity(repositoryClass=TagArticleRepository::class)
 */
class TagArticle
{
    use TimestampableEntity;

    /**
     * @ORM\Id()
     * @ORM\ManyToOne(targetEntity=Tag::class, inversedBy="articles", fetch="EAGER")
     * @ORM\JoinColumn(nullable=false)
     * @ORM\OrderBy({"priority" = "DESC"})
     */
    private $tag;

    /**
     * @ORM\Id()
     * @ORM\ManyToOne(targetEntity=Article::class, inversedBy="tags")
     * @ORM\JoinColumn(nullable=false)
     */
    private $article;
...
````

It works FANTASTIC, but now I'm stuck at the select of "all articles associated to (at least) one specific tag". 

I'm really flying blind here, but in my `ArticleRepository` I tried this:

````
$this->createQueryBuilder('a')
    ->leftJoin( 'a.tags', 'tags')
    ->addSelect('tags')
    ->andWhere('a.tags IN(:myTag)')
    ->setParameter('myTag', $myTagEntity)
    ->getQuery()
    ->getResult();
````

As expected, this fails miserably because `$myTagEntity` is a Tag entity while is probably expecting a TagArticle.

So... what's the right syntax here?

Thanks

**Comment by ZaneCEO** [comment]
Ok, I found out by trial-and-error that it works like this:

````
->andWhere('tags.tag IN(:tag)')
->setParameter('tag', [$myTagEntity->getId()]);
````

It's almost OK, but now all the articles seem to be associated only to the `$myTagEntity`, even if they have other tags. What can I do to fix this?

**Comment by bocharsky-bw** [comment]
Hey @ZaneCEO ,

Now, when you have a separate (standalone) entity called `TagArticle`, you should join it in your queries instead of doing that simple ManyToMany syntax, i.e in your `ArticleRepository`:

```
$this->createQueryBuilder('a')
    ->innerJoin( 'a.tagArticle', 'tagArticle')
    ->innerJoin( 'tagArticle.tag, 'tag')
    // ...
```

I think you confused yourself with naming of your fields... With `TagArticle` entity now you should have:
- Tag::$tagArticles
- Article::$tagArticles
- TagArticle::$tag
- TagArticle::$article

You should understand that calling `Article->getTags()` will return you collection of `TagArticle` not `Tag` entities. So, I'd recommend you to rename those properties and methods to make it obvious to you. I.e. that `Article->getTags()` should be renamed to `Article->getTagArticles()`. And if you want to get the tag, you will need to do something like:

```
foreach (Article->getTagArticles() as $tagArticle) {
    $tagArticle->getTag(); // This will give you an instance of your Tag entity.
}
```

And so, when writing your queries in repositories, you should count on this and use 2 joins now, first to join the intermediate table called `TagArticle`, and second - the actual Tag or Article table depends on in which repository you're writing this query (see my first example)

I hope this helps!

Cheers!
